name: Daily Auto Commit

on:
  workflow_dispatch:  # Permite ejecutar el workflow manualmente
  schedule:
    - cron: '40 3 * * *'  # Se ejecuta todos los días a las 03:40 UTC

jobs:
  commit:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Permitir que el GITHUB_TOKEN tenga permisos de escritura

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}
      id: import-gpg

    - name: Update last_update.txt with current date
      run: |
        echo "Última actualización: $(date)" > last_update.txt

    - name: Commit and push changes
      run: |
        git config --local user.name "RomanBrandariz"
        git config --local user.email "branr0@hotmail.com"
        git config --local user.signingkey ${{ steps.import-gpg.outputs.keyid }}
        git config --local commit.gpgSign true
        git add last_update.txt
        git commit -m "Auto-update: $(date)"
        git push
