name: Daily Auto Commit

on:
  workflow_dispatch:  # Permite ejecutar el workflow manualmente
  schedule:
    - cron: '40 3 * * *' # Se ejecuta todos los días a las 03:40 UTC


jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Update last_update.txt with current date
      run: |
        echo "Última actualización: $(date)" > last_update.txt

    - name: Commit and push changes
      run: |
        git config --local user.name "GitHub Actions"  # Configura el nombre localmente
        git config --local user.email "actions@github.com"  # Configura el email localmente
        git add last_update.txt
        git commit -m "Auto-update: $(date)"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Usa el token para autenticar
